# Use Node.js official image
FROM node:22

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json

COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY backend/ .

# Expose the backend port
EXPOSE 8000

# Set environment variables (Use env_file to load from .env)
ENV PORT=8000
ENV CORS_ORIGIN=http://localhost:5173
ENV ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
ENV ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
ENV REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
ENV REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
ENV MONGODB_URI=${MONGODB_URI}
ENV NODE_ENV=production

# Start the application
CMD ["npm", "start"]
